"""
GORVAX GAME FACTORY — Starter Script
Inicia os 3 servicos na ordem correta com um unico comando.
"""

import subprocess
import sys
import os
import time
import signal
import threading
import io
import urllib.request
import urllib.error
from pathlib import Path

# Fix Windows console encoding
sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding="utf-8", errors="replace")
sys.stderr = io.TextIOWrapper(sys.stderr.buffer, encoding="utf-8", errors="replace")

ROOT_DIR = os.path.dirname(os.path.abspath(__file__))
BACKEND_DIR = ROOT_DIR
DASHBOARD_DIR = os.path.join(ROOT_DIR, "dashboard")
GAME_DIR = os.path.join(ROOT_DIR, "game")

processes: list[subprocess.Popen] = []


def log(emoji: str, msg: str) -> None:
    print(f"  {emoji}  {msg}", flush=True)


def shutdown(sig=None, frame=None) -> None:
    print("\n", flush=True)
    log("!", "Encerrando todos os servicos...")
    for p in reversed(processes):
        try:
            p.terminate()
            p.wait(timeout=5)
        except Exception:
            p.kill()
    log("*", "GORVAX GAME FACTORY encerrada. Ate mais!")
    sys.exit(0)


signal.signal(signal.SIGINT, shutdown)
signal.signal(signal.SIGTERM, shutdown)


def stream_output(process: subprocess.Popen, name: str, emoji: str) -> None:
    """Stream process output with a prefix."""
    if process.stdout is None:
        return
    for line in iter(process.stdout.readline, ""):
        line = line.rstrip()
        if line:
            print(f"  {emoji} [{name}] {line}", flush=True)


def start_service(
    name: str,
    emoji: str,
    cmd: list[str],
    cwd: str,
    env: dict | None = None,
) -> subprocess.Popen:
    """Start a service and return its process."""
    log(emoji, f"Iniciando {name}...")
    merged_env = {**os.environ, **(env or {})}
    process = subprocess.Popen(
        cmd,
        cwd=cwd,
        stdout=subprocess.PIPE,
        stderr=subprocess.STDOUT,
        text=True,
        encoding="utf-8",
        errors="replace",
        env=merged_env,
        shell=True,
    )
    processes.append(process)

    # Stream output in background thread
    thread = threading.Thread(
        target=stream_output, args=(process, name, emoji), daemon=True
    )
    thread.start()
    return process


def check_npm_installed(directory: str, name: str) -> None:
    """Check if node_modules exists, if not run npm install."""
    node_modules = os.path.join(directory, "node_modules")
    if not os.path.isdir(node_modules):
        log(">>", f"Instalando dependencias do {name}...")
        subprocess.run(
            ["npm", "install"],
            cwd=directory,
            shell=True,
            check=True,
        )


def sync_dashboard_env() -> None:
    """Sync API key from root .env to dashboard/.env.local.

    The dashboard needs NEXT_PUBLIC_GORVAX_API_KEY to authenticate
    with the backend API and WebSocket. This function reads the key
    from the root .env and writes/updates the dashboard .env.local.
    """
    env_file = Path(ROOT_DIR) / ".env"
    dashboard_env = Path(DASHBOARD_DIR) / ".env.local"

    # Read API key from root .env
    api_key = ""
    backend_port = "8000"
    if env_file.exists():
        for line in env_file.read_text(encoding="utf-8").splitlines():
            if line.startswith("GORVAX_API_KEY=") and line.split("=", 1)[1].strip():
                api_key = line.split("=", 1)[1].strip()
            if line.startswith("BACKEND_PORT="):
                backend_port = line.split("=", 1)[1].strip()

    if not api_key:
        return

    # Write dashboard .env.local
    content = (
        f"# Auto-generated by start.py — do not edit manually\n"
        f"NEXT_PUBLIC_API_URL=http://localhost:{backend_port}\n"
        f"NEXT_PUBLIC_WS_URL=ws://localhost:{backend_port}/ws\n"
        f"NEXT_PUBLIC_GORVAX_API_KEY={api_key}\n"
    )
    dashboard_env.write_text(content, encoding="utf-8")
    log(">>", f"Dashboard .env.local sincronizado (API key: {api_key[:8]}...)")


def main() -> None:
    print(flush=True)
    print("  ====================================================", flush=True)
    print("       GORVAX GAME FACTORY - Iniciando servicos...         ", flush=True)
    print("  ====================================================", flush=True)
    print(flush=True)

    # --- 0. Sync API key to dashboard .env.local ---
    sync_dashboard_env()

    # --- 1. Check dependencies ---
    check_npm_installed(DASHBOARD_DIR, "Dashboard")
    check_npm_installed(GAME_DIR, "Game")

    # --- 2. Start Backend (must be first) ---
    python_exe = sys.executable
    backend = start_service(
        name="Backend",
        emoji="[PY]",
        cmd=[python_exe, "-m", "backend.main"],
        cwd=BACKEND_DIR,
    )

    # INT-06: Health check with retry instead of blind sleep
    # DEV-03: Use configured backend port instead of hardcoded 8000
    backend_port = os.getenv("BACKEND_PORT", "8000")

    # Load API key from .env for authenticated health check
    api_key = os.getenv("GORVAX_API_KEY", "")
    if not api_key:
        env_file = Path(ROOT_DIR) / ".env"
        if env_file.exists():
            for line in env_file.read_text(encoding="utf-8").splitlines():
                if line.startswith("GORVAX_API_KEY=") and line.split("=", 1)[1].strip():
                    api_key = line.split("=", 1)[1].strip()

    log("[PY]", "Aguardando backend ficar pronto...")
    backend_ready = False
    for attempt in range(1, 16):
        if backend.poll() is not None:
            log("!!", f"Backend morreu durante inicializacao (codigo {backend.returncode})")
            shutdown()
            return
        try:
            url = f"http://localhost:{backend_port}/api/v1/health"
            req = urllib.request.Request(url)
            if api_key:
                req.add_header("X-API-Key", api_key)
            urllib.request.urlopen(req, timeout=3)
            backend_ready = True
            log("[PY]", f"Backend pronto! (tentativa {attempt})")
            break
        except urllib.error.HTTPError as e:
            if e.code == 401:
                # Auth works, server is up — just not the right key
                backend_ready = True
                log("[PY]", f"Backend respondendo (auth ativa, tentativa {attempt})")
                break
            time.sleep(2)
        except (urllib.error.URLError, OSError):
            time.sleep(2)

    if not backend_ready:
        log("!!", "Backend nao respondeu apos 15 tentativas, continuando mesmo assim...")
        if backend.poll() is not None:
            log("!!", f"Backend morreu durante inicializacao (codigo {backend.returncode})")
            shutdown()
            return

    # --- 3. Start Dashboard ---
    dashboard = start_service(
        name="Dashboard",
        emoji="[UI]",
        cmd=["npm", "run", "dev"],
        cwd=DASHBOARD_DIR,
        env={"PORT": "3000"},
    )
    time.sleep(2)
    if dashboard.poll() is not None:
        log("!!", f"Dashboard morreu durante inicializacao (codigo {dashboard.returncode})")
        shutdown()
        return

    # --- 4. Start Game ---
    game = start_service(
        name="Game",
        emoji="[GM]",
        cmd=["npm", "run", "dev"],
        cwd=GAME_DIR,
    )
    time.sleep(2)
    if game.poll() is not None:
        log("!!", f"Game morreu durante inicializacao (codigo {game.returncode})")
        shutdown()
        return

    # --- 5. Print summary ---
    game_port = os.getenv("GAME_PORT", "5174")
    print(flush=True)
    print("  ====================================================", flush=True)
    print("       Tudo rodando com sucesso!                       ", flush=True)
    print("  ====================================================", flush=True)
    print(flush=True)
    print(f"  [PY] Backend:    http://localhost:{backend_port}", flush=True)
    print(f"  [PY] API Docs:   http://localhost:{backend_port}/docs", flush=True)
    print("  [UI] Dashboard:  http://localhost:3000", flush=True)
    print(f"  [GM] Game:       http://localhost:{game_port}", flush=True)
    print(flush=True)
    print("  Pressione Ctrl+C para encerrar tudo", flush=True)
    print("  ====================================================", flush=True)
    print(flush=True)

    # --- 6. Keep alive until Ctrl+C ---
    try:
        while True:
            # Check if any process died
            for p in processes:
                if p.poll() is not None:
                    log("!!", f"Um servico encerrou (codigo {p.returncode})")
            time.sleep(2)
    except KeyboardInterrupt:
        shutdown()


if __name__ == "__main__":
    main()
